{
 "title": "Database Usage",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Top users",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "baseQuery": "{\"collection\": \"$collection\"}",
     "collection": "dbusage",
     "dtfield": "lastseen",
     "groupbyfield": "userid",
     "labelfield": "{{name}}",
     "queryText": "db.users.aggregate([\r\n  {\"$match\": {\"_type\": \"user\"}},\r\n  {\r\n    \"$project\": {\r\n      \"name\": \"$name\",\r\n      \"value\": \"$dbusage\", \"_id\": 0\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"value\": -1\r\n    }\r\n  },\r\n  {\r\n    \"$limit\": 15\r\n  }\r\n])",
     "valueexp": "{\"$sum\": \"$size\"}"
    }
   ]
  },
  {
   "title": "Top Customers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "baseQuery": "{\"collection\": \"$collection\"}",
     "collection": "dbusage",
     "dtfield": "_created",
     "groupbyfield": "userid",
     "labelfield": "{{name}}",
     "queryText": "db.users.aggregate([\r\n  {\"$match\": { \"_type\": \"customer\" } }, \r\n  {\"$project\": \r\n    {\"_id\":0,  \"value\": \"$dbusage\", \"name\": \"$name\"}\r\n    },\r\n  {\r\n    \"$sort\": {\r\n      \"value\": -1\r\n    }\r\n  },\r\n  {\r\n    \"$limit\": 50\r\n  }\r\n])",
     "valueexp": "{\"$sum\": \"$size\"}"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "baseQuery": "{\"collection\": \"$collection\"}",
     "collection": "dbusage",
     "dtfield": "lastseen",
     "groupbyfield": "userid",
     "labelfield": "{{name}}",
     "queryText": "db.users.aggregate([\r\n  {\"$match\": {\"_type\": \"user\"}},\r\n  {\r\n    \"$project\": {\r\n      \"name\": \"$name\",\r\n      \"username\": \"$username\",\r\n      \"company\": \"$company\",\r\n      \"lastseen\": \"$lastseen\",\r\n      \"value\": \"$dbusage\", \"_id\": 0\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"value\": -1\r\n    }\r\n  },\r\n  {\r\n    \"$limit\": 75\r\n  }\r\n])",
     "valueexp": "{\"$sum\": \"$size\"}"
    }
   ]
  },
  {
   "title": "Top Customers",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "dbusage",
     "dtfield": "_created",
     "groupbyfield": "collection",
     "labelfield": "{{collection}}",
     "queryText": "db.users.aggregate([\r\n  {\"$match\": { \"_type\": \"customer\" } }, \r\n  {\"$project\": \r\n    {\"_id\":0,  \"value\": \"$dbusage\", \"name\": \"$name\"}\r\n    },\r\n  {\r\n    \"$sort\": {\r\n      \"value\": -1\r\n    }\r\n  },\r\n  {\r\n    \"$limit\": 50\r\n  }\r\n])",
     "valueexp": "{\"$sum\": \"$size\"}"
    }
   ]
  },
  {
   "title": "Top Collections",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "dbusage",
     "dtfield": "_created",
     "groupbyfield": "collection",
     "labelfield": "{{collection}}",
     "queryText": "db.dbusage.aggregate([\r\n  \r\n  {\r\n    \"$addFields\": {\r\n      \"__labelfield\": {\r\n        \"$concat\": [\r\n          \"\",\r\n          {\r\n            \"$toString\": \"$collection\"\r\n          },\r\n          \"\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": {\r\n        \"dt\": {\r\n          \"$subtract\": [\r\n            {\r\n              \"$subtract\": [\r\n                \"$timestamp\",\r\n                \"$to\"\r\n              ]\r\n            },\r\n            {\r\n              \"$mod\": [\r\n                {\r\n                  \"$subtract\": [\r\n                    \"$timestamp\",\r\n                    \"$to\"\r\n                  ]\r\n                },\r\n                \"$intervalMs\"\r\n              ]\r\n            }\r\n          ]\r\n        },\r\n        \"collection\": \"$collection\"\r\n      },\r\n      \"value\": {\r\n        \"$sum\": \"$size\"\r\n      },\r\n      \"ts\": {\r\n        \"$max\": \"$timestamp\"\r\n      },\r\n      \"name\": {\r\n        \"$first\": \"$__labelfield\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"value\": -1\r\n    }\r\n  },\r\n  {\r\n    \"$limit\": 15\r\n  }\r\n])",
     "valueexp": "{\"$sum\": \"$size\"}"
    }
   ]
  },
  {
   "title": "Top Collections",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "dbusage",
     "dtfield": "_created",
     "groupbyfield": "collection",
     "labelfield": "{{collection}}",
     "queryText": "db.dbusage.aggregate([\r\n  {\r\n    \"$addFields\": {\r\n      \"__labelfield\": {\r\n        \"$concat\": [\r\n          \"\",\r\n          {\r\n            \"$toString\": \"$collection\"\r\n          },\r\n          \"\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": {\r\n        \"dt\": {\r\n          \"$subtract\": [\r\n            {\r\n              \"$subtract\": [\r\n                \"$timestamp\",\r\n                \"$to\"\r\n              ]\r\n            },\r\n            {\r\n              \"$mod\": [\r\n                {\r\n                  \"$subtract\": [\r\n                    \"$timestamp\",\r\n                    \"$to\"\r\n                  ]\r\n                },\r\n                \"$intervalMs\"\r\n              ]\r\n            }\r\n          ]\r\n        },\r\n        \"collection\": \"$collection\"\r\n      },\r\n      \"value\": {\r\n        \"$sum\": \"$size\"\r\n      },\r\n      \"ts\": {\r\n        \"$max\": \"$timestamp\"\r\n      },\r\n      \"name\": {\r\n        \"$first\": \"$__labelfield\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"value\": -1\r\n    }\r\n  },\r\n  {\r\n    \"$unset\": \"_id\"\r\n  },\r\n  {\r\n    \"$limit\": 50\r\n  }\r\n])",
     "valueexp": "{\"$sum\": \"$size\"}"
    }
   ]
  }
 ]
}