{
 "title": "Openflow Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "46ce24eba84848dc077c9851ceeecdfc"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nodejs_heap_size_used_bytes{ofid=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Nodered Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nodejs_heap_size_used_bytes{domain=\"\",ofid=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "API Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nodejs_heap_size_used_bytes{domain!=\"\",ofid=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openflow_websocket_online_clients{ofid=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "LocalOpenflows",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (hostname) (nodejs_heap_size_used_bytes{ofid=\"46ce24eba84848dc077c9851ceeecdfc\"}))\r"
    }
   ]
  },
  {
   "title": "response times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, avg(rate(openflow_mongodb_query_seconds_bucket{ofid=~\"$instance\",collection!=\"\"}[1m])) by (le)) != 0",
     "legendFormat": "query",
     "valueexp": "{\"$sum\": 1}"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(openflow_mongodb_aggregate_seconds_bucket{ofid=~\"$instance\",collection!=\"\"}[1m])) by (le)) != 0",
     "legendFormat": "aggregate"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(openflow_mongodb_insert_seconds_bucket{ofid=~\"$instance\",collection!=\"\"}[1m])) by (le)) != 0",
     "legendFormat": "insert"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(openflow_mongodb_insertmany_seconds_bucket{ofid=~\"$instance\",collection!=\"\"}[1m])) by (le)) != 0",
     "legendFormat": "insertmany"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(openflow_mongodb_update_seconds_bucket{ofid=~\"$instance\",collection!=\"\"}[1m])) by (le)) != 0",
     "legendFormat": "update"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(openflow_mongodb_updatemany_seconds_bucket{ofid=~\"$instance\",collection!=\"\"}[1m])) by (le)) != 0",
     "legendFormat": "updatemany"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(openflow_mongodb_replace_seconds_bucket{ofid=~\"$instance\",collection!=\"\"}[1m])) by (le)) != 0",
     "legendFormat": "replace"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(openflow_mongodb_delete_seconds_bucket{ofid=~\"$instance\",collection!=\"\"}[1m])) by (le)) != 0",
     "legendFormat": "delete"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(openflow_mongodb_deletemany_seconds_bucket{ofid=~\"$instance\",collection!=\"\"}[1m])) by (le)) != 0",
     "legendFormat": "deletemany"
    }
   ]
  },
  {
   "title": "response times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(1, avg(rate(openflow_mongodb_query_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le, collection)) != 0",
     "legendFormat": "query {{collection}}",
     "valueexp": "{\"$sum\": 1}"
    },
    {
     "expr": "histogram_quantile(1, avg(rate(openflow_mongodb_aggregate_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le, collection)) != 0",
     "legendFormat": "aggregate {{collection}}"
    },
    {
     "expr": "histogram_quantile(1, avg(rate(openflow_mongodb_insert_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le, collection)) != 0",
     "legendFormat": "insert {{collection}}"
    },
    {
     "expr": "histogram_quantile(1, avg(rate(openflow_mongodb_insertmany_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le, collection)) != 0",
     "legendFormat": "insertmany {{collection}}"
    },
    {
     "expr": "histogram_quantile(1, avg(rate(openflow_mongodb_update_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le, collection)) != 0",
     "legendFormat": "update {{collection}}"
    },
    {
     "expr": "histogram_quantile(1, avg(rate(openflow_mongodb_updatemany_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le, collection)) != 0",
     "legendFormat": "updatemany {{collection}}"
    },
    {
     "expr": "histogram_quantile(1, avg(rate(openflow_mongodb_replace_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le, collection)) != 0",
     "legendFormat": "replace {{collection}}"
    },
    {
     "expr": "histogram_quantile(1, avg(rate(openflow_mongodb_delete_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le, collection)) != 0",
     "legendFormat": "delete {{collection}}"
    },
    {
     "expr": "histogram_quantile(1, avg(rate(openflow_mongodb_deletemany_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le, collection)) != 0",
     "legendFormat": "deletemany {{collection}}"
    }
   ]
  },
  {
   "title": "NodeJS Heap Usage for $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(nodejs_heap_size_used_bytes{ofid=~\"$instance\"}) by (hostname)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Online Clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(openflow_websocket_online_clients{ofid=~\"$instance\", agent!=\"\"}) by (agent)",
     "legendFormat": "{{agent}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Item cache per type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(openflow_item_cache_count{ofid=~\"$instance\"}) by (type)",
     "legendFormat": "{{type}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Item cache per host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(openflow_item_cache_count{ofid=~\"$instance\"}) by (ofid, hostname)",
     "legendFormat": "{{hostname}} ",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "node count diff",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "openflow_nodered_node_duration_sum{ofid=~\"$instance\"} - openflow_nodered_node_duration_sum{ofid=~\"$instance\"} offset $__interval > 0\r\n\r",
     "legendFormat": "{{nodetype}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "OpenRPA memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "Process_PrivateWorkingSet{ofid=~\"$instance\"}",
     "legendFormat": "{{host}} {{username}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "node count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(openflow_nodered_node_duration_sum{ofid=~\"$instance\"}) by (nodetype) != 0",
     "legendFormat": "{{nodetype}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Running OpenRPA Workflows",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "openrpa_workflow_running_count{ofid=~\"$instance\"} != 0",
     "legendFormat": "{{host}} {{username}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "query times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, sum(rate(openflow_mongodb_query_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le,collection)) != 0",
     "legendFormat": "{{collection}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Number of queries per api node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(rate(openflow_mongodb_query_seconds_count{ofid=~\"$instance\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "aggregate times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, sum(rate(openflow_mongodb_aggregate_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le,collection)) != 0",
     "legendFormat": "{{collection}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Number of aggregates per api node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(rate(openflow_mongodb_aggregate_seconds_count{ofid=~\"$instance\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "insert times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, sum(rate(openflow_mongodb_insert_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le,collection)) != 0",
     "legendFormat": "{{collection}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Number of inserts per api node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(rate(openflow_mongodb_insert_seconds_count{ofid=~\"$instance\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "replace times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, sum(rate(openflow_mongodb_replace_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le,collection)) != 0",
     "legendFormat": "{{collection}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Number of replaces per api node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(rate(openflow_mongodb_replace_seconds_count{ofid=~\"$instance\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "insertmany times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, sum(rate(openflow_mongodb_insertmany_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le,collection)) != 0",
     "legendFormat": "{{collection}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Number of insertmanys per api node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(rate(openflow_mongodb_insertmany_seconds_count{ofid=~\"$instance\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "update times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, sum(rate(openflow_mongodb_update_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le,collection)) != 0",
     "legendFormat": "{{collection}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Number of updates per api node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(rate(openflow_mongodb_update_seconds_count{ofid=~\"$instance\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "update many times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, sum(rate(openflow_mongodb_updatemany_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le,collection)) != 0",
     "legendFormat": "{{collection}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Number of updatemanys per api node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(rate(openflow_mongodb_updatemany_seconds_count{ofid=~\"$instance\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "delete times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, sum(rate(openflow_mongodb_delete_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le,collection)) != 0",
     "legendFormat": "{{collection}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Number of deletes per api node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(rate(openflow_mongodb_delete_seconds_count{ofid=~\"$instance\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "deletemany times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, sum(rate(openflow_mongodb_deletemany_seconds_bucket{ofid=~\"$instance\"}[1m])) by (le,collection)) != 0",
     "legendFormat": "{{collection}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Number of deletemanys per api node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(rate(openflow_mongodb_deletemany_seconds_count{ofid=~\"$instance\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "WebSocket Message Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(openflow_websocket_messages_duration_seconds_bucket{ofid=~\"$instance\"}[1m]) !=0) by (command, le)) !=0\n",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Number of websocket messages per api node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(rate(openflow_websocket_messages_duration_seconds_count{ofid=~\"$instance\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "node duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, sum(rate(openflow_nodered_node_duration_bucket{ofid=~\"$instance\"}[1m])) by (le, nodetype))",
     "legendFormat": "{{nodetype}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Number of websocket messages ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "sum(rate(openflow_websocket_messages_duration_seconds_count{ofid=~\"$instance\"}[1m])) by (command)",
     "legendFormat": "{{hostname}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Grafana Query Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "baseQuery": "{}",
     "collection": "entities",
     "dtfield": "_created",
     "expr": "histogram_quantile(0.95, sum(rate(openflow_http_grafana_query_request_duration_bucket{ofid=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "{{nodetype}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  }
 ]
}