{
 "title": "RPA Usage",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "username",
    "query": "db.users.find({\"_type\": \"user\", \"lastseen\": { \"$gte\" : \"$from\", \"$lte\" : \"$to\"}}).projection({\"name\":1,\"_id\":0})"
   }
  ]
 },
 "panels": [
  {
   "title": "Logins per user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{\"name\": {\"$in\": \"$username\"}}",
     "collection": "audit",
     "dtfield": "_created",
     "groupbyfield": "name2",
     "labelfield": "{{name}}",
     "queryText": "db.audit.aggregate([\r\n  {\r\n    \"$match\": {\r\n      \"name\": {\r\n        \"$in\": \"{Allan Zimmermann,allan5,allan6,macuser,allan,postnord01,sloif,sloifopenrpa,sloifnordicengineeringaps}\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"__labelfield\": {\r\n        \"$concat\": [\r\n          {\r\n            \"$toString\": \"$name\"\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": {\r\n        \"dt\": {\r\n          \"$subtract\": [\r\n            {\r\n              \"$subtract\": [\r\n                \"$_created\",\r\n                \"1970-01-01T00:00:00.000Z\"\r\n              ]\r\n            },\r\n            {\r\n              \"$mod\": [\r\n                {\r\n                  \"$subtract\": [\r\n                    \"$_created\",\r\n                    \"1970-01-01T00:00:00.000Z\"\r\n                  ]\r\n                },\r\n                \"$intervalMs\"\r\n              ]\r\n            }\r\n          ]\r\n        },\r\n        \"name\": \"$name\"\r\n      },\r\n      \"value\": {\r\n        \"$sum\": 1\r\n      },\r\n      \"ts\": {\r\n        \"$max\": \"$_created\"\r\n      },\r\n      \"name\": {\r\n        \"$max\": \"$__labelfield\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"ts\": -1\r\n    }\r\n  },\r\n  {\r\n    \"$limit\": \"$maxDataPoints\"\r\n  }\r\n])",
     "target": "db.audit.aggregate ( \n  [  \n    { \"$match\": { \"name\": {\"$in\": \"$username\"},  \"_created\": { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n    {\"$project\": { \n    \t\"day\": {\"$dayOfMonth\": \"$_created\"},\n    \t\"month\": {\"$month\": \"$_created\"},\n    \t\"year\": {\"$year\": \"$_created\"},\n    \t\"h\": {\"$hour\":\"$_created\"},\n    \t\"ts\": \"$_created\",\n        \"name\": \"$name\"\n    } },\n    {\"$group\": {\n    \t\"_id\": { \"name\": \"$name\", \"h\": \"$h\", \"day\": \"$day\", \"month\": \"$month\", \"year\" : \"$year\" },\n        \"ts\": {\"$max\" : \"$ts\"},\n        \"name\": {\"$max\" : \"$name\"},\n    \t\"value\": {\"$sum\" : 1}\n    }},\n    {\"$sort\":{\"ts\": 1}}\n  ]\n)",
     "type": "timeserie",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Login Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "targets": [
    {
     "collection": "audit",
     "dtfield": "_created",
     "queryText": "db.audit.aggregate([\n  {\n    \"$group\": {\n      \"_id\": {\n        \"dt\": {\n          \"$subtract\": [\n            {\n              \"$subtract\": [\n                \"$_created\",\n                \"1970-01-01T00:00:00.000Z\"\n              ]\n            },\n            {\n              \"$mod\": [\n                {\n                  \"$subtract\": [\n                    \"$_created\",\n                    \"1970-01-01T00:00:00.000Z\"\n                  ]\n                },\n                \"$intervalMs\"\n              ]\n            }\n          ]\n        }\n      },\n      \"value\": {\n        \"$sum\": 1\n      },\n      \"ts\": {\n        \"$max\": \"$_created\"\n      }\n    }\n  },\n  {\n    \"$sort\": {\n      \"ts\": -1, \"name\": -1\n    }\n  },\n  {\n    \"$limit\": \"$maxDataPoints\"\n  }\n])",
     "target": "db.audit.aggregate ( \n  [  \n    { \"$match\": {  \"name\": {\"$in\": \"$username\"}, \"_created\": { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n    {\"$project\": { \n        \"name\": \"$name\"\n    } },\n    {\"$group\": {\n    \t\"_id\": { \"name\": \"$name\" },\n        \"name\": {\"$max\" : \"$name\"},\n    \t\"value\": {\"$sum\" : 1}\n    }},\n    {\"$project\": { \n        \"name\": 1, \"value\": 1, \"_id\": 0\n    } },\n    {\"$sort\":{\"value\": -1}},\n    {\"$limit\": 30}\n  ]\n)",
     "type": "table",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "collection": "openrpa_instances",
     "dtfield": "_created",
     "groupbyfield": "name",
     "labelfield": "{{name}}",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  },
  {
   "title": "Workflow runs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseQuery": "{\"_createdby\": {\"$in\": \"$username\"}}",
     "collection": "openrpa_instances",
     "dtfield": "_created",
     "queryText": "{\"_createdby\": {\"$in\": \"$username\"}}",
     "target": "db.openrpa_instances.aggregate ( \n  [  \n    { \"$match\": { \"_createdby\": {\"$in\": \"$username\"},  \"_created\": { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n    {\"$project\": { \n    \t\"day\": {\"$dayOfMonth\": \"$_created\"},\n    \t\"month\": {\"$month\": \"$_created\"},\n    \t\"year\": {\"$year\": \"$_created\"},\n    \t\"h\": {\"$hour\":\"$_created\"},\n    \t\"ts\": \"$_created\",\n        \"name\": \"$name\"\n    } },\n    {\"$group\": {\n    \t\"_id\": {  \"h\": \"$h\", \"day\": \"$day\", \"month\": \"$month\", \"year\" : \"$year\" },\n        \"ts\": {\"$max\" : \"$ts\"},\n    \t\"value\": {\"$sum\" : 1}\n    }},\n    {\"$sort\":{\"ts\": 1}}\n  ]\n)",
     "type": "timeserie",
     "valueexp": "{\"$sum\": 1}"
    }
   ]
  }
 ]
}