{
 "title": "Workflow Stats",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Workflow Run Time Per Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "db.openrpa_instances.aggregate ( \n  [  \n    { \"$match\": {  \"_created\": { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n    {\"$project\": { \n    \t\"day\": {\"$dayOfMonth\": \"$_created\"},\n    \t\"month\": {\"$month\": \"$_created\"},\n    \t\"year\": {\"$year\": \"$_created\"},\n    \t\"h\": {\"$hour\":\"$_created\"},\n    \t\"ts\": \"$_created\",\n        \"name\": \"$name\",\n        \"ms\": {\"$subtract\":[ \"$_modified\", \"$_created\" ] }\n    } },\n    {\"$group\": {\n    \t\"_id\": {  \"createdby\": \"$createdby\", \"name\": \"$name\" , \"h\": \"$h\", \"day\": \"$day\", \"month\": \"$month\", \"year\" : \"$year\" },\n        \"ts\": {\"$max\" : \"$ts\"},\n        \"name\": {\"$max\" : \"$name\"},\n    \t\"value\": {\"$avg\" : \"$ms\"}\n    }},\n    {\"$sort\":{\"ts\": 1}}\n  ]\n)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Workflows Runs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "db.openrpa_instances.aggregate ( \n  [  \n    { \"$match\": {  \"_created\": { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n    {\"$project\": { \n        \"name\": \"$name\", \"createdby\": \"$_createdby\"\n    } },\n    {\"$group\": {\n    \t\"_id\": { \"createdby\": \"$createdby\", \"name\": \"$name\" },\n        \"name\": {\"$max\" : \"$name\"},\n        \"createdby\": {\"$max\" : \"$createdby\"},\n    \t\"value\": {\"$sum\" : 1}\n    }},\n    {\"$sort\":{\"value\": -1}}, {\"$limit\": 50},\n     {\"$project\": {  \"_id\": 0 } }\n ]\n)",
     "type": "table"
    }
   ]
  },
  {
   "title": "Workflow Runs per User",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "db.openrpa_instances.aggregate ( \n  [  \n    { \"$match\": {  \"_created\": { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n    {\"$project\": { \n        \"name\": \"$_createdby\", \"ts\": \"$to\"\n    } },\n    {\"$group\": {\n    \t\"_id\": { \"name\": \"$name\" },\n        \"name\": {\"$max\" : \"$name\"},\n        \"ts\": {\"$max\" : \"$ts\"},\n    \t\"value\": {\"$sum\" : 1}\n        \n    }},\n    {\"$sort\":{\"value\": -1}}, {\"$limit\":10}\n    , {\"$project\": { \"_id\": 0 }}\n  ]\n)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Workflow Runs per User",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "db.openrpa_instances.aggregate ( \n  [  \n    { \"$match\": {  \"_created\": { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n    {\"$project\": { \n        \"userid\": \"$_createdbyid\"\n    } },\n    {\"$group\": {\n    \t\"_id\": { \"userid\": \"$userid\"},\n        \"userid\": {\"$max\" : \"$userid\"},\n    \t\"count\": {\"$sum\" : 1}\n    }},\n    { \"$lookup\":\n     {\n       \"from\": \"users\",\n       \"localField\": \"userid\",\n       \"foreignField\": \"_id\",\n       \"as\": \"user\"\n     } },\n      {\n        \"$unwind\": \"$user\"\n      },\n    {\"$project\": { \n        \"username\": \"$user.username\",  \"name\": \"$user.name\", \"count\": \"$count\", \"_id\": 0\n    } },\n    {\"$sort\":{\"count\": -1}}\n  ]\n)",
     "type": "table"
    }
   ]
  }
 ]
}